-- MySQL Script generated by MySQL Workbench
-- Thu Apr  3 14:38:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shounenshowdown
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shounenshowdown
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shounenshowdown` ;
USE `shounenshowdown` ;

-- -----------------------------------------------------
-- Table `shounenshowdown`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`card` (
  `crd_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `crd_name` VARCHAR(150) NOT NULL,
  `crd_description` VARCHAR(400) NOT NULL,
  `crd_show` VARCHAR(150) NOT NULL,
  `crd_level` INT(10) NOT NULL,
  `crd_hp` INT(10) NOT NULL,
  `crd_power` INT(10) NOT NULL,
  PRIMARY KEY (`crd_id`),
  UNIQUE INDEX `crd_id_UNIQUE` (`crd_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shounenshowdown`.`move`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`move` (
  `mov_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `mov_crd_id` INT(10) UNSIGNED NOT NULL,
  `mov_name` VARCHAR(150) NOT NULL,
  `mov_description` VARCHAR(400) NOT NULL,
  `mov_type` VARCHAR(150) NOT NULL,
  `mov_class` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`mov_id`),
  UNIQUE INDEX `mov_id_UNIQUE` (`mov_id` ASC) VISIBLE,
  INDEX `fk_move_card1_idx` (`mov_crd_id` ASC) VISIBLE,
  CONSTRAINT `fk_move_card1`
    FOREIGN KEY (`mov_crd_id`)
    REFERENCES `shounenshowdown`.`card` (`crd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shounenshowdown`.`pack`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`pack` (
  `pck_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pck_name` VARCHAR(150) NOT NULL,
  `pck_price` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`pck_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shounenshowdown`.`pack_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`pack_card` (
  `pcd_pck_id` INT(11) UNSIGNED NOT NULL,
  `pcd_crd_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`pcd_pck_id`, `pcd_crd_id`),
  INDEX `fk_pack_card_card1_idx` (`pcd_crd_id` ASC) VISIBLE,
  CONSTRAINT `fk_pack_card_pack1`
    FOREIGN KEY (`pcd_pck_id`)
    REFERENCES `shounenshowdown`.`pack` (`pck_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pack_card_card1`
    FOREIGN KEY (`pcd_crd_id`)
    REFERENCES `shounenshowdown`.`card` (`crd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shounenshowdown`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`user` (
  `usr_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usr_username` VARCHAR(150) NOT NULL,
  `usr_email` VARCHAR(150) NOT NULL,
  `usr_password` VARCHAR(2555) NOT NULL,
  `usr_salt` VARCHAR(100) NOT NULL,
  `usr_avatar` VARCHAR(150) NULL DEFAULT NULL,
  `usr_balance` INT(10) NULL DEFAULT 100,
  `usr_rank` INT(10) NULL DEFAULT 500,
  `usr_xp` INT(10) NULL DEFAULT 0,
  `usr_wins` INT(10) NULL DEFAULT 0,
  `usr_losses` INT(10) NULL DEFAULT 0,
  PRIMARY KEY (`usr_id`),
  UNIQUE INDEX `usr_id_UNIQUE` (`usr_id` ASC) VISIBLE,
  UNIQUE INDEX `usr_username_UNIQUE` (`usr_username` ASC) VISIBLE,
  UNIQUE INDEX `usr_email_UNIQUE` (`usr_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shounenshowdown`.`user_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shounenshowdown`.`user_card` (
  `ucd_usr_id` INT(11) UNSIGNED NOT NULL,
  `ucd_crd_id` INT(11) UNSIGNED NOT NULL,
  `ucd_deck` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ucd_usr_id`, `ucd_crd_id`),
  INDEX `fk_user_card_card1_idx` (`ucd_crd_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_card_user`
    FOREIGN KEY (`ucd_usr_id`)
    REFERENCES `shounenshowdown`.`user` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_card_card1`
    FOREIGN KEY (`ucd_crd_id`)
    REFERENCES `shounenshowdown`.`card` (`crd_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
